### ISSUE TITLE
Error: Invalid Cucumber JSON file

### ISSUE THREAD

**Issue by majidmakhdomi** [maciejmaciejewski/azure-pipelines-cucumber#16] opened 2020-05-22 14:40 UTC
Hi Maciej,

I have been able to successfully publish Cucumber HTML reports for few application using the PublishCucumberReport. But I am getting the below error in one of my applications.

The YAML is

  - task: PublishCucumberReport@1
    condition: succeededOrFailed()
    inputs:
      jsonDir: 'target/'
      outputPath: 'target/cucumber-html-reports'
      theme: 'bootstrap'
      reportSuiteAsScenarios: true

There is a cucumber.json in the target (provided as jsonDir) but the error is showing in target/classes/META-INF/spring-configuration-metadata.json. I am attaching both files (as .txt as .json was not allowed). Can you please check and let me know what the issue could be.

Error:

/azp/agent/_work/_tasks/PublishCucumberReport_83c082c0-5032-11ea-8fab-bbe0f0fcf287/1.0.4/reporter/node_modules/cucumber-html-reporter/lib/jsonDir.js:26
            throw new Error('Invalid Cucumber JSON file found under ' + options.jsonDir + ': ' + file);
            ^
Error: Invalid Cucumber JSON file found under /azp/agent/_work/34/s/target/: /azp/agent/_work/34/s/target/classes/META-INF/spring-configuration-metadata.json
    at mergeJSONS (/azp/agent/_work/_tasks/PublishCucumberReport_83c082c0-5032-11ea-8fab-bbe0f0fcf287/1.0.4/reporter/node_modules/cucumber-html-reporter/lib/jsonDir.js:26:19)
    at Array.map (<anonymous>)
    at Object.collectJSONS (/azp/agent/_work/_tasks/PublishCucumberReport_83c082c0-5032-11ea-8fab-bbe0f0fcf287/1.0.4/reporter/node_modules/cucumber-html-reporter/lib/jsonDir.js:48:11)
    at Object.generate (/azp/agent/_work/_tasks/PublishCucumberReport_83c082c0-5032-11ea-8fab-bbe0f0fcf287/1.0.4/reporter/node_modules/cucumber-html-reporter/lib/reporter.js:492:17)
    at generateReport (/azp/agent/_work/_tasks/PublishCucumberReport_83c082c0-5032-11ea-8fab-bbe0f0fcf287/1.0.4/reporter/node_modules/cucumber-html-reporter/index.js:30:21)
    at Object.<anonymous> (/azp/agent/_work/_tasks/PublishCucumberReport_83c082c0-5032-11ea-8fab-bbe0f0fcf287/1.0.4/reporter/script.js:17:1)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
##[warning]Error: Failed to run script

[spring-configuration-metadata.son.txt](https://github.com/maciejmaciejewski/azure-pipelines-cucumber/files/4668626/spring-configuration-metadata.son.txt)

[cucumber.json.txt](https://github.com/maciejmaciejewski/azure-pipelines-cucumber/files/4668653/cucumber.json.txt)

**Comment by maciejmaciejewski** [comment] 2020-05-23 06:44
Hello @majidmakhdomi 
The problem is with the third party library I am using for generating HTML report.
It takes path as an input and check for every single JSON file in this directory, no matter if it is cucumber or not. For non-cucumber files it will throw an error, so as a solution I would suggest to use more specific path like ./target/test-results/cucumber which will assure correct plugin input.

**Comment by majidmakhdomi** [comment] 2020-05-26 07:34
Hi Maciej,

I tried you suggested solution and it worked. Thank you!

**Comment by maciejmaciejewski** [comment] 2020-05-26 07:42
Hi @majidmakhdomi 
I am glad it worked, closing the issue.

**Closed by maciejmaciejewski** 2020-05-26 07:42 UTC

**Comment by bunyaminpinar** [comment] 2023-01-27 09:12
Make sure **target** directory doen't exist in .gitignore file.
